# Generated by Django 5.2 on 2025-05-11 18:50

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='payout_schedule',
            field=models.CharField(blank=True, help_text='The payout schedule for the deal', max_length=255),
        ),
        migrations.AddField(
            model_name='deal',
            name='projected_payout',
            field=models.CharField(blank=True, help_text='The projected payout for the deal', max_length=255),
        ),
        migrations.AddField(
            model_name='deal',
            name='revenue_share',
            field=models.CharField(blank=True, help_text='The revenue share for the deal', max_length=255),
        ),
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
