# Generated by Django 5.2 on 2025-05-11 18:51

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_deal_payout_schedule_deal_projected_payout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
