# Generated by Django 5.2 on 2025-05-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_alter_deal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='keywords',
            field=models.CharField(blank=True, help_text='The keywords for the deal, comma separated', max_length=255),
        ),
    ]
