# Generated by Django 5.2 on 2025-05-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_deal_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='commission_type',
            field=models.CharField(blank=True, help_text='The commission type for the deal', max_length=255),
        ),
    ]
