# Generated by Django 5.2 on 2025-09-23 07:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_deal_commission_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(verbose_name='period end')),
                ('clicks', models.IntegerField(default=0, verbose_name='clicks')),
                ('impressions', models.IntegerField(default=0, verbose_name='impressions')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='deals.deal')),
            ],
            options={
                'verbose_name': 'Deal Stats',
                'verbose_name_plural': 'Deal Stats',
                'indexes': [models.Index(fields=['deal', 'period_start', 'period_end'], name='deals_deals_deal_id_9cf956_idx')],
                'unique_together': {('deal', 'period_start', 'period_end')},
            },
        ),
    ]
