# Generated by Django 5.2 on 2025-09-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_dealstats'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dealstats',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='deal',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo of the company offering the deal', null=True, upload_to='deal_logos/'),
        ),
        migrations.AddConstraint(
            model_name='dealstats',
            constraint=models.UniqueConstraint(fields=('deal', 'period_start', 'period_end'), name='unique_deal_period'),
        ),
    ]
