# Generated by Django 5.2 on 2025-09-22 21:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('weekly_ftds', models.IntegerField(default=0, verbose_name='weekly FTDs')),
                ('top_geo', models.CharField(blank=True, max_length=100, verbose_name='top GEO')),
                ('total_affiliates', models.IntegerField(default=0, verbose_name='total affiliates')),
                ('total_deals', models.IntegerField(default=0, verbose_name='total deals')),
                ('week_starting', models.DateField(verbose_name='week starting')),
            ],
            options={
                'verbose_name': 'Community Stats',
                'verbose_name_plural': 'Community Stats',
                'ordering': ['-week_starting'],
            },
        ),
    ]
