# Generated by Django 5.2 on 2025-09-23 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitystats',
            name='total_affiliates',
        ),
        migrations.RemoveField(
            model_name='communitystats',
            name='total_deals',
        ),
    ]
