upstream backend_server {
  server web:8000;
}

server {
    listen 80;
    server_name _;

    # Django static files
    location /static/ {
        alias /var/www/django/static/;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
    }

    # Django media files
    location /media/ {
        alias /var/www/django/media/;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
    }

    # Send all other requests to Django
    location / {
      proxy_pass http://backend_server;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_redirect off;
    }
}