# Generated by Django 5.2 on 2025-05-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='type',
            field=models.CharField(choices=[('verify_account', 'Verify Account'), ('reset_password', 'Reset Password')], default='verify_account', max_length=20, verbose_name='type'),
        ),
    ]
