# Generated by Django 5.2 on 2025-05-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_verificationcode_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='verificationcode',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['verify_account', 'reset_password'])), name='users_verificationcode_type_valid'),
        ),
    ]
