# Generated by Django 5.2 on 2025-05-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_verificationcode_users_verificationcode_type_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(max_length=12, unique=True, verbose_name='verification code'),
        ),
    ]
