# Generated by Django 5.2 on 2025-05-11 09:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_verificationcode_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnboarding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('brand_name', models.CharField(max_length=255, verbose_name='brand name')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('marketing_methods', models.CharField(blank=True, help_text='List of marketing methods used by the user', null=True, verbose_name='marketing methods')),
                ('heard_from', models.CharField(max_length=255, verbose_name='heard from')),
                ('feedback_message', models.TextField(blank=True, verbose_name='feedback message')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User Onboarding',
                'verbose_name_plural': 'User Onboardings',
            },
        ),
    ]
