# Generated by Django 5.2 on 2025-05-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_useronboarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useronboarding',
            name='marketing_methods',
            field=models.CharField(blank=True, default='Whatsapp', help_text='List of marketing methods used by the user', verbose_name='marketing methods'),
            preserve_default=False,
        ),
    ]
