# Generated by Django 5.2 on 2025-05-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0008_alter_useronboarding_marketing_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='useronboarding',
            name='affliate_experience',
            field=models.CharField(blank=True, max_length=255, verbose_name='affliate experience'),
        ),
        migrations.AddField(
            model_name='useronboarding',
            name='ftds_deliverability_per_month',
            field=models.IntegerField(
                blank=True, default=0, verbose_name='ftds deliverability per month'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useronboarding',
            name='type_of_deals_wanted',
            field=models.CharField(blank=True, max_length=255, verbose_name='type of deals wanted'),
        ),
    ]
