# Generated by Django 5.2 on 2025-09-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_useronboarding_affliate_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='last login IP'),
        ),
        migrations.AddField(
            model_name='user',
            name='locale',
            field=models.CharField(default='en', max_length=10, verbose_name='locale'),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50, verbose_name='timezone'),
        ),
    ]
